spring:
    application:
        name: core

    mongodb:
        host: ${MONGO_HOST}
        port: ${MONGO_PORT}
        username: ${MONGO_APP_USERNAME}
        password: ${MONGO_APP_PASSWORD}
        database: ${MONGO_INITDB_DATABASE}
        authentication-database: ${MONGO_INITDB_DATABASE}

app:
    snapshots:
        lifetime-in-days: ${SNAPSHOTS_LIFETIME_IN_DAYS}
        test-lifetime-in-days: ${SNAPSHOTS_TEST_LIFETIME_IN_DAYS}
        sleep-up-to-before-fetch-in-milliseconds: ${SNAPSHOTS_SLEEP_UP_TO_BEFORE_FETCH_IN_MILLISECONDS}

    telegram:
        bot-token: ${TELEGRAM_BOT_TOKEN}
        chat-id: ${TELEGRAM_CHAT_ID}

    parser:
        url: ${PARSER_URL}

    job-board-cookie:
        djinni: ${JOB_BOARD_COOKIE_DJINNI}