spring:
    application:
        name: core
    mongodb:
        host: ${MONGO_HOST:mongodb}
        port: ${MONGO_PORT:27017}
        username: ${MONGO_INITDB_ROOT_USERNAME:root}
        password: ${MONGO_INITDB_ROOT_PASSWORD:root}
        database: ${MONGO_INITDB_DATABASE:vacancies-monitoring}
        authentication-database: admin

app:
    snapshots:
        lifetime-in-days: ${SNAPSHOTS_LIFETIME_IN_DAYS:7}
        fetch-delay-in-seconds: ${SNAPSHOTS_FETCH_DELAY_IN_SECONDS:60}

    telegram:
        bot-token: ${TELEGRAM_BOT_TOKEN:1234}
        chat-id: ${TELEGRAM_CHAT_ID:-1001234}

    parser:
        url: ${PARSER_URL}